/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns session state and issues a readable XSRF-TOKEN cookie. Call again after login/logout. */
        get: operations["session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Cached startup/job validation. Does not perform filesystem reads. */
        get: operations["sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["systemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Scan history, oldest first with a stable committed cutoff. */
        get: operations["scans"];
        put?: never;
        /** @description Queue whole registered roots, inventory metadata, hash only repeated-size regular files, then publish duplicate analysis. At most ten unfinished jobs and five creations per actor per minute. */
        post: operations["createScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scanId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Captured source scope, coverage and durable progress. Completion is inventory-only. */
        get: operations["scan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Job history, oldest first with a stable committed cutoff. */
        get: operations["jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Durable counters; discovery total is unknown. Waiting for I/O means no checkpoint for five seconds, not proof of a kernel hang. */
        get: operations["job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Request cooperative pause. PAUSED acknowledges that worker handles have reached a safe point. */
        post: operations["pauseJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Validate captured configuration, all selected roots and root identities before requeueing a PAUSED or INTERRUPTED job. */
        post: operations["resumeJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cancel wins pause races. Running work acknowledges cancellation at a safe point. Terminal completion cannot be relabeled. */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Paged structured errors; committed inventory remains accessible. */
        get: operations["jobErrors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scanId}/directories/{locationId}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Committed observations from PostgreSQL only. No source reads. Unknown totals and partial coverage are explicit. */
        get: operations["children"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observations/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One immutable scan observation with append-only instability evidence; no live file access. */
        get: operations["observation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hash-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Explicit bounded selection in one frozen scan. Normal requests reuse accepted hashes without refreshing their timestamps; forceRehash reads anew. A conflicting fresh digest invalidates active evidence. Jobs use the same admission, control and lease rules as scans. */
        post: operations["createHashJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observations/{id}/hash-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["hashAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{id}/duplicate-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["duplicateGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/duplicate-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["duplicateGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{id}/files/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Database-only AND filters. Text contains/exact compares literal UTF-8 bytes, case-sensitive; % and _ are data. Raw base64 supports non-UTF-8 names. Sorts use raw bytes, exact integers/nanoseconds, UUID tiebreaker and nulls last. Cursors bind filters, committed entry cutoff and evidence/query/annotation revisions; changes return 409 CURSOR_STALE. Future signature/content filters return 422. */
        post: operations["searchFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scanId}/directories/{locationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Saved directory context and at most 256 ancestor breadcrumbs; never probes sources. */
        get: operations["directory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}/annotation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Location notes relative to the requested observation, or most recently inventoried observation. Default version 0. File changes preserve notes and set needsReview. */
        get: operations["annotation"];
        /** @description Expected-version optimistic concurrency; 409 preserves the previous value. Saving explicitly reaffirms the selected observation as the note baseline. Plain-text memo max 20,000 Unicode code points; at most 100 manual tags. Audited. */
        put: operations["updateAnnotation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Stored observations across scans in sequence order. History is never duplicate-copy evidence. */
        get: operations["locationHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Bounded catalog; literal normalized-label search. Labels trim Unicode whitespace, compare NFKC then Locale.ROOT lowercase, and preserve entered display form. This never normalizes filenames. */
        get: operations["tags"];
        put?: never;
        /** @description Creates a reusable manual tag; normalized-label duplicates return 409. */
        post: operations["createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Optimistic catalog rename. Existing association labels update; captured selections become needsReview. */
        patch: operations["renameTag"];
        trace?: never;
    };
    "/scans/{id}/selections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Atomically freezes all matching or explicit IDs in the captured view. 1–500 rows; overflow is rejected without truncation. Captures annotation versions/snapshots and accepted attempt IDs. Actor-bound, expires in 24 hours. New inventory rows never extend it. */
        post: operations["freezeSelection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/selections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Frozen count/bytes/query and paged captured members, with current state and capturedAnnotation. Member annotation/tag/evidence or analysis changes set needsReview. Does not mutate captured targets. */
        get: operations["selection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/annotation-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Atomic, audited, single-use frozen bulk tagging/review-state edit. Stale members or expired selection return 409 with zero updates. New rows alone do not block a captured batch. Existing memo baselines are preserved. Idempotency-Key replays the original response. */
        post: operations["applyAnnotationBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Session: {
            authenticated: boolean;
            username: string | null;
        };
        Health: {
            /** @enum {string} */
            status: "UP" | "DOWN";
        };
        SystemInfo: {
            name: string;
            version: string;
            /** @constant */
            milestone: "M3";
            platform: string;
            /** @constant */
            sourcePolicy: "READ_ONLY";
            /** @constant */
            scanAvailable: true;
            configurationRevision: string;
            /** @constant */
            inventoryOnly: false;
        };
        SourceList: {
            configurationRevision: string;
            sources: components["schemas"]["Source"][];
        };
        Source: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sourceInstanceId: string;
            key: string;
            label: string;
            containerPath: string;
            enabled: boolean;
            crossMounts: boolean;
            status: string;
            detail: string;
            excludedMountCount: number;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            code: string;
            detail: string;
            /** Format: uuid */
            correlationId: string;
            retriable: boolean;
        };
        ScanRequest: {
            name: string;
            sourceIds: string[];
            /**
             * @default SHA-256
             * @enum {string}
             */
            hashAlgorithm: "SHA-256";
            /**
             * @default false
             * @constant
             */
            includeSignatureCandidates: false;
            /**
             * @default false
             * @constant
             */
            textIndexingEnabled: false;
        };
        ScanCreated: {
            /** Format: uuid */
            scanId: string;
            /** Format: uuid */
            jobId: string;
            /** @description False for new M2 scans. Replaying a historical M1 idempotency key preserves its original true value. */
            inventoryOnly: boolean;
        };
        Job: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scanId: string;
            /** @enum {string} */
            type: "INVENTORY" | "SCAN" | "HASH";
            /** @enum {string} */
            phase: "INVENTORY" | "CANDIDATE_SELECTION" | "HASHING" | "ANALYSIS";
            /** @enum {string} */
            state: "QUEUED" | "RUNNING" | "PAUSE_REQUESTED" | "PAUSED" | "CANCEL_REQUESTED" | "CANCELLED" | "INTERRUPTED" | "COMPLETED" | "COMPLETED_WITH_ERRORS" | "FAILED";
            version: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
            /** Format: date-time */
            heartbeatAt: string | null;
            /** Format: date-time */
            checkpointAt: string | null;
            /** Format: uuid */
            currentSourceId: string | null;
            currentPath: string | null;
            blockCode: string | null;
            /** @constant */
            leaseSeconds: 60;
            /** @constant */
            heartbeatSeconds: 10;
            discoveredEntries: string;
            discoveredFiles: string;
            discoveredDirectories: string;
            discoveredBytes: string;
            errorCount: string;
            skippedEntries: string;
            pendingWork: string;
            completedWork: string;
            totalKnown: boolean;
            waitingForIo: boolean;
            candidateFiles: string;
            candidateBytes: string;
            hashedFiles: string;
            reusedFiles: string;
            physicalBytesRead: string;
            usefulBytesHashed: string;
        };
        ScanSource: {
            /** Format: uuid */
            sourceId: string;
            /** Format: uuid */
            sourceInstanceId: string;
            label: string;
            /** Format: uuid */
            rootLocationId: string;
            /** @enum {string} */
            coverage: "COMPLETE" | "PARTIAL" | "UNAVAILABLE" | "EXCLUDED_BY_POLICY";
        };
        Scan: {
            /** Format: uuid */
            id: string;
            name: string;
            configurationRevision: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            inventoryFrozenAt: string | null;
            inventoryOnly: boolean;
            analysisAvailable: boolean;
            job: components["schemas"]["Job"];
            sources: components["schemas"]["ScanSource"][];
            analysisId: string | null;
            evidenceRevision: string;
            latestJob: components["schemas"]["Job"];
            activeHashJobs: components["schemas"]["Job"][];
        };
        Observation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scanId: string;
            /** Format: uuid */
            locationId: string;
            /** Format: uuid */
            sourceId: string;
            /** Format: uuid */
            sourceInstanceId: string;
            /** Format: uuid */
            parentLocationId: string | null;
            name: string;
            path: string;
            relativePathBytesBase64: string;
            nameBytesBase64: string;
            extension: string | null;
            /** @enum {string} */
            entryType: "DIRECTORY" | "REGULAR" | "SYMLINK" | "SPECIAL" | "UNKNOWN";
            sizeBytes: string | null;
            metadataMask: number | null;
            mode: number | null;
            mtimeNanos: number | null;
            ctimeNanos: number | null;
            birthNanos: number | null;
            inode: string | null;
            mountId: string | null;
            deviceMajor: string | null;
            deviceMinor: string | null;
            linkCount: string | null;
            blocks: string | null;
            uid: string | null;
            gid: string | null;
            mtimeSeconds: string | null;
            ctimeSeconds: string | null;
            birthSeconds: string | null;
            filesystemType: string | null;
            symlinkTargetBytesBase64: string | null;
            /** Format: date-time */
            mtime: string | null;
            /** Format: date-time */
            ctime: string | null;
            discoveryStatus: string;
            /** @enum {string|null} */
            directoryCoverage: "COMPLETE" | "PARTIAL" | "UNAVAILABLE" | "EXCLUDED_BY_POLICY" | null;
            unstable: boolean;
            /** Format: date-time */
            observedAt: string;
            hash?: components["schemas"]["HashEvidence"];
        };
        JobError: {
            id: string;
            /** Format: uuid */
            locationId: string;
            displayPath: string;
            code: string;
            detail: string;
            /** Format: date-time */
            createdAt: string;
        };
        ScanPage: {
            items: components["schemas"]["Scan"][];
            nextCursor: string | null;
        };
        JobPage: {
            items: components["schemas"]["Job"][];
            nextCursor: string | null;
        };
        ErrorPage: {
            items: components["schemas"]["JobError"][];
            nextCursor: string | null;
        };
        ChildrenPage: {
            items: components["schemas"]["Observation"][];
            nextCursor: string | null;
            /** Format: uuid */
            parentLocationId: string | null;
            displayPath: string;
        };
        HashAttempt: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            jobId: string;
            /** @constant */
            algorithm: "SHA-256";
            digest: string | null;
            bytesRead: string;
            /** Format: date-time */
            startedAt: string;
            completedAt: string | null;
            reasons: ("DUPLICATE_SIZE" | "MANUAL" | "FORCED_RECHECK")[];
            /** @enum {string} */
            outcome: "READING" | "ACCEPTED" | "FAILED" | "INTERRUPTED" | "STOPPED" | "CONFLICT";
            errorCode: string | null;
            errorDetail: string | null;
            preFingerprint: {
                [key: string]: unknown;
            } | null;
            postFingerprint: {
                [key: string]: unknown;
            } | null;
        };
        HashEvidence: {
            /** @enum {string} */
            status: "INELIGIBLE" | "STALE" | "ACCEPTED" | "PENDING" | "FAILED" | "NOT_REQUESTED_UNIQUE_SIZE" | "NOT_REQUESTED";
            pending: boolean;
            accepted: components["schemas"]["HashAttempt"] | null;
            latestAttempt: components["schemas"]["HashAttempt"] | null;
            invalidationCode: string | null;
        };
        HashRequest: {
            /** Format: uuid */
            scanId: string;
            observationIds?: string[];
            /** @default false */
            forceRehash: boolean;
            /**
             * Format: uuid
             * @description Actor-owned unexpired frozen selection. Supply exactly one of observationIds or selectionId. Stale selection returns 409.
             */
            selectionId?: string;
        } & (unknown | unknown);
        HashCreated: {
            /** Format: uuid */
            scanId: string;
            /** Format: uuid */
            jobId: string;
        };
        HashAttemptPage: {
            items: components["schemas"]["HashAttempt"][];
            nextCursor: string | null;
        };
        DuplicateGroup: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            analysisId: string;
            /** Format: uuid */
            scanId: string;
            sizeBytes: string;
            /** @constant */
            algorithm: "SHA-256";
            digest: string;
            pathCount: string;
            objectCount: string | null;
            /** @enum {string} */
            identityStatus: "ALIASED_MOUNTS_UNCERTAIN" | "IDENTITY_UNKNOWN" | "HARD_LINKS_PRESENT" | "DISTINCT_OBJECTS";
            /** @enum {string} */
            evidenceLevel: "HASH_IDENTICAL" | "STALE";
            sourceIds: string[];
            pathLogicalBytes: string;
            independentObjectLogicalBytes: string | null;
            maximumDuplicateCopyLogicalBytes: string | null;
            physicalSavingsBytes: null;
        };
        GroupPage: {
            analysisId: string | null;
            evidenceRevision: string;
            /** @enum {string} */
            status: "NOT_AVAILABLE" | "CURRENT" | "NEEDS_REBUILD";
            items: components["schemas"]["DuplicateGroup"][];
            nextCursor: string | null;
        };
        GroupDetail: {
            group: components["schemas"]["DuplicateGroup"];
            members: {
                observation: components["schemas"]["Observation"];
                hash: components["schemas"]["HashAttempt"];
            }[];
            nextCursor: string | null;
        };
        Tag: {
            /** Format: uuid */
            id: string;
            label: string;
            version: string;
        };
        TagPage: {
            items: components["schemas"]["Tag"][];
            nextCursor: string | null;
        };
        /** @enum {string} */
        ReviewState: "UNREVIEWED" | "REVIEWED" | "KEEP" | "REMOVAL_REVIEW";
        Annotation: {
            /** Format: uuid */
            locationId: string;
            /** Format: uuid */
            observationId: string;
            version: string;
            memo: string;
            reviewState: components["schemas"]["ReviewState"];
            tags: components["schemas"]["Tag"][];
            needsReview: boolean;
            /** Format: uuid */
            baselineObservationId: string | null;
            /** Format: date-time */
            updatedAt: string | null;
            updatedBy: string | null;
        };
        AnnotationUpdate: {
            /** Format: uuid */
            observationId: string;
            expectedVersion: string;
            memo: string;
            tagIds: string[];
            reviewState: components["schemas"]["ReviewState"];
        };
        SearchFilters: {
            nameContains?: string;
            pathContains?: string;
            nameExact?: string;
            pathExact?: string;
            extension?: string;
            memoContains?: string;
            /** Format: uuid */
            sourceId?: string;
            /** Format: uuid */
            subtreeLocationId?: string;
            /** Format: uuid */
            parentLocationId?: string;
            /** Format: uuid */
            duplicateGroupId?: string;
            minBytes?: string;
            maxBytes?: string;
            /**
             * Format: date-time
             * @description UTC ISO instant ending in Z. Lower inclusive, upper exclusive; nanoseconds retained.
             */
            mtimeFrom?: string;
            /**
             * Format: date-time
             * @description UTC ISO instant ending in Z. Lower inclusive, upper exclusive; nanoseconds retained.
             */
            mtimeTo?: string;
            nameBytesBase64?: string;
            pathBytesBase64?: string;
            /** @enum {string} */
            entryType?: "REGULAR" | "DIRECTORY" | "SYMLINK" | "SPECIAL" | "UNKNOWN";
            checksum?: string;
            checksumPrefix?: string;
            /** @enum {string} */
            hashStatus?: "ACCEPTED" | "PENDING" | "FAILED" | "STALE" | "INELIGIBLE" | "NOT_REQUESTED" | "NOT_REQUESTED_UNIQUE_SIZE";
            /** @enum {string} */
            duplicateState?: "DUPLICATE" | "STALE" | "NOT_GROUPED";
            tagIds?: string[];
            /**
             * @description Server default: ANY.
             * @enum {string}
             */
            tagMode?: "ANY" | "ALL";
            reviewState?: components["schemas"]["ReviewState"];
            hasError?: boolean;
            stale?: boolean;
            annotationsNeedReview?: boolean;
        };
        SearchQuery: {
            filters?: components["schemas"]["SearchFilters"];
            /**
             * @description Server default: path.
             * @enum {string}
             */
            sort?: "name" | "path" | "size" | "mtime" | "checksumTime";
            /**
             * @description Server default: ASC.
             * @enum {string}
             */
            direction?: "ASC" | "DESC";
            /** @description Server default: 100. */
            limit?: number;
            cursor?: string | null;
        };
        SearchEntry: components["schemas"]["Observation"] & {
            /** @enum {string} */
            hashStatus: "ACCEPTED" | "PENDING" | "FAILED" | "STALE" | "INELIGIBLE" | "NOT_REQUESTED" | "NOT_REQUESTED_UNIQUE_SIZE";
            checksum: string | null;
            /** Format: date-time */
            checksumCompletedAt: string | null;
            /** @enum {string} */
            duplicateState: "DUPLICATE" | "STALE" | "NOT_GROUPED";
            /** Format: uuid */
            duplicateGroupId: string | null;
            stale: boolean;
            hasError: boolean;
            annotation: components["schemas"]["Annotation"];
        };
        SearchPage: {
            items: components["schemas"]["SearchEntry"][];
            nextCursor: string | null;
            viewToken: string;
            evidenceRevision: string;
            annotationRevision: string;
            /** Format: uuid */
            analysisId: string | null;
        };
        HistoryPage: {
            items: (components["schemas"]["Observation"] & {
                annotation: components["schemas"]["Annotation"];
                /** @enum {string} */
                hashStatus: "ACCEPTED" | "PENDING" | "FAILED" | "STALE" | "INELIGIBLE" | "NOT_REQUESTED" | "NOT_REQUESTED_UNIQUE_SIZE";
            })[];
            nextCursor: string | null;
        };
        Directory: {
            /** Format: uuid */
            locationId: string;
            path: string;
            coverage: string | null;
            breadcrumbs: {
                /** Format: uuid */
                locationId: string;
                name: string;
                path: string;
            }[];
        };
        SelectionRequest: {
            query: components["schemas"]["SearchQuery"];
            viewToken: string;
            observationIds?: string[];
        };
        Selection: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scanId: string;
            /** Format: uuid */
            analysisId: string | null;
            count: string;
            totalBytes: string;
            /** Format: date-time */
            createdAt: string | null;
            /** Format: date-time */
            expiresAt: string | null;
            expired: boolean;
            /** Format: date-time */
            appliedAt: string | null;
            query: components["schemas"]["SearchQuery"];
            /** @description Members lacking size. totalBytes sums known sizes only. */
            unknownSizes: string;
        };
        SelectionDetail: components["schemas"]["Selection"] & {
            needsReview: boolean;
            items: (components["schemas"]["SearchEntry"] & {
                capturedAnnotation: components["schemas"]["Annotation"];
            })[];
            nextCursor: string | null;
        };
        AnnotationBatch: {
            /** Format: uuid */
            selectionId: string;
            addTagIds?: string[];
            removeTagIds?: string[];
            reviewState?: components["schemas"]["ReviewState"];
        };
        BatchResult: {
            /** Format: uuid */
            selectionId: string;
            updatedCount: string;
        };
        TagCreate: {
            label: string;
        };
        TagUpdate: {
            label: string;
            expectedVersion: string;
        };
    };
    responses: {
        /** @description Structured error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
        Csrf: string;
        /** @description Opaque cursor scoped to this view and its committed sequence cutoff. Refresh without a cursor to see newly committed rows. */
        Cursor: string;
        Limit: number;
        /** @description Retained at least 24 hours (currently indefinitely). Repeating the same normalized request returns its original response, even at capacity. */
        Idempotency: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    username: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Authenticated; rotated HttpOnly session cookie */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
        };
    };
    sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    systemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Implemented capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application and database ready; source availability is independent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    scans: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to this view and its committed sequence cutoff. Refresh without a cursor to see newly committed rows. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored metadata / durable state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    createScan: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
                /** @description Retained at least 24 hours (currently indefinitely). Repeating the same normalized request returns its original response, even at capacity. */
                "Idempotency-Key"?: components["parameters"]["Idempotency"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Queued; not completed */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanCreated"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    scan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored metadata / durable state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    jobs: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to this view and its committed sequence cutoff. Refresh without a cursor to see newly committed rows. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored metadata / durable state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored metadata / durable state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    pauseJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
            };
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored metadata / durable state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    resumeJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
            };
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored metadata / durable state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
            };
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored metadata / durable state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    jobErrors: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to this view and its committed sequence cutoff. Refresh without a cursor to see newly committed rows. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored metadata / durable state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    children: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to this view and its committed sequence cutoff. Refresh without a cursor to see newly committed rows. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                scanId: string;
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored metadata / durable state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildrenPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    observation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored metadata / durable state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observation"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    createHashJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
                /** @description Retained at least 24 hours (currently indefinitely). Repeating the same normalized request returns its original response, even at capacity. */
                "Idempotency-Key"?: components["parameters"]["Idempotency"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HashRequest"];
            };
        };
        responses: {
            /** @description Saved result */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HashCreated"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    hashAttempts: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to this view and its committed sequence cutoff. Refresh without a cursor to see newly committed rows. */
                cursor?: components["parameters"]["Cursor"];
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HashAttemptPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    duplicateGroups: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to this view and its committed sequence cutoff. Refresh without a cursor to see newly committed rows. */
                cursor?: components["parameters"]["Cursor"];
                limit?: number;
                /** @description Pin the published revision while paging. Omitting it selects the current revision; a cursor from a different revision is rejected. */
                analysisId?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    duplicateGroup: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to this view and its committed sequence cutoff. Refresh without a cursor to see newly committed rows. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupDetail"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    searchFiles: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchQuery"];
            };
        };
        responses: {
            /** @description Stored application data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    directory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored application data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Directory"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    annotation: {
        parameters: {
            query?: {
                observationId?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored application data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Annotation"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    updateAnnotation: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotationUpdate"];
            };
        };
        responses: {
            /** @description Stored application data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Annotation"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    locationHistory: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to this view and its committed sequence cutoff. Refresh without a cursor to see newly committed rows. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored application data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    tags: {
        parameters: {
            query?: {
                query?: string;
                /** @description Opaque cursor scoped to this view and its committed sequence cutoff. Refresh without a cursor to see newly committed rows. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored application data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    createTag: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Stored application data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    renameTag: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description Stored application data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    freezeSelection: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectionRequest"];
            };
        };
        responses: {
            /** @description Stored application data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Selection"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    selection: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to this view and its committed sequence cutoff. Refresh without a cursor to see newly committed rows. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored application data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelectionDetail"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    applyAnnotationBatch: {
        parameters: {
            query?: never;
            header: {
                /** @description Retained at least 24 hours (currently indefinitely). Repeating the same normalized request returns its original response, even at capacity. */
                "Idempotency-Key"?: components["parameters"]["Idempotency"];
                /** @description Exact current XSRF-TOKEN cookie value; session cookie is separately HttpOnly. */
                "X-XSRF-TOKEN": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotationBatch"];
            };
        };
        responses: {
            /** @description Stored application data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
}
