import { test, expect } from '@playwright/test';
import { createHash } from 'node:crypto';

test.use({actionTimeout:15000});
test('catalog dry run, explicit unique-size check, derived labels, observation creation and immutable export',async({page,context},testInfo)=>{
  test.skip(process.env['FNORD_EXPECT_NATIVE_FIXTURES']!=='true','Generated native fixture server required.');
  test.setTimeout(240000);
  await page.goto('/'); await page.getByLabel('Username').fill('operator'); await page.getByLabel('Password',{exact:true}).fill(process.env['FNORD_TEST_PASSWORD']!);
  await page.getByRole('button',{name:'Sign in',exact:true}).click(); await expect(page.getByRole('heading',{name:'Inventory ready'})).toBeVisible();
  const token=(await context.cookies()).find(c=>c.name==='XSRF-TOKEN')!.value;
  const headers={'X-XSRF-TOKEN':token};
  const scans=await (await page.request.get('/api/v1/scans')).json();
  const scan=scans.items.at(-1); expect(scan).toBeDefined();
  const name='<img src=x onerror=alert(1)> known fixture';
  const record={schemaVersion:1,name,memo:'=inert memo,\n"quoted"',tags:['fixture label'],sizeBytes:'24',algorithm:'SHA-256',checksum:createHash('sha256').update('x'.repeat(24)).digest('hex'),filename:'original-name.txt',filenameMatchMode:'ADVISORY',enabled:true};
  await page.getByRole('link',{name:'Signatures',exact:true}).click();
  const imports=page.getByRole('region',{name:'Catalog import'});
  const upload=async(records:unknown[])=>{
    await imports.getByLabel('Catalog file',{exact:true}).setInputFiles({name:'benign-signatures.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schemaVersion:1,signatures:records}))});
    await imports.getByRole('button',{name:'Validate and stage catalog',exact:true}).click();
  };
  await upload([record,{...record,name:'Invalid fixture',checksum:'bad'}]);
  await expect(imports.getByRole('heading',{name:'Dry run · INVALID',exact:true})).toBeVisible();
  await expect(imports.getByRole('button',{name:/Apply all/})).toBeDisabled();
  await upload([record]);
  await expect(imports.getByRole('heading',{name:'Dry run · VALID',exact:true})).toBeVisible();
  const before=await (await page.request.get('/api/v1/signatures?query='+encodeURIComponent(name))).json(); expect(before.items).toHaveLength(0);
  await imports.getByRole('button',{name:'Apply all 1 staged records atomically',exact:true}).click();
  await expect(imports.getByRole('heading',{name:'Dry run · APPLIED',exact:true})).toBeVisible();
  const catalog=await (await page.request.get('/api/v1/signatures?query='+encodeURIComponent(name))).json(); const signature=catalog.items[0];
  const searched=await (await page.request.post(`/api/v1/scans/${scan.id}/files/search`,{headers,data:{filters:{nameExact:'file-0004.txt'}}})).json(); const observation=searched.items[0];
  await expect.poll(async()=> (await (await page.request.get('/api/v1/observations/'+observation.id+'/signatures')).json()).checkStatus,{timeout:60000}).toBe('HASH_REQUIRED');
  expect((await (await page.request.get('/api/v1/observations/'+observation.id)).json()).hash.status).toBe('NOT_REQUESTED_UNIQUE_SIZE');
  const inspect=async()=>{
    await page.goto(`/scans/${scan.id}/files`); await page.getByLabel('Filename contains',{exact:true}).fill('file-0004.txt'); await page.getByRole('button',{name:'Search stored files',exact:true}).click();
    await page.getByRole('button',{name:'file-0004.txt',exact:true}).click(); await expect(page.getByRole('region',{name:'Signature findings'})).toBeVisible();
  };
  await inspect(); await expect(page.getByRole('region',{name:'Signature findings'})).toContainText('HASH_REQUIRED');
  await page.getByLabel('Location memo',{exact:true}).fill('Manual note survives signature disable'); await page.getByRole('button',{name:'Save location notes',exact:true}).click();
  await expect(page.getByText('Location notes saved.',{exact:true})).toBeVisible();
  await page.goto(`/scans/${scan.id}`); const check=page.getByRole('region',{name:'Check known signatures'});
  await check.getByRole('button',{name:'Preview signature candidate reads',exact:true}).click();
  await expect(check).toContainText('1 previously unhashed files · 24 bytes');
  await expect(async()=>{
    const confirm=check.getByRole('button',{name:'Authorize reads and check signatures',exact:true}); if(await confirm.isVisible()) await confirm.click();
    await expect(check.getByRole('status')).toContainText('Signature check queued',{timeout:1500});
  }).toPass({timeout:75000,intervals:[1000,5000,10000]});
  await expect.poll(async()=> (await (await page.request.get('/api/v1/observations/'+observation.id+'/signatures')).json()).matchStatus,{timeout:60000}).toBe('MATCHED');
  await inspect(); const findings=page.getByRole('region',{name:'Signature findings'});
  await expect(findings.getByRole('heading',{name,exact:true})).toBeVisible(); await expect(findings).toContainText('fixture label');
  expect(await page.locator('img').count()).toBe(0); await page.screenshot({path:testInfo.outputPath('m4-findings.png'),fullPage:true});
  await findings.getByRole('link',{name:'Create signature from this observation',exact:true}).click();
  await page.getByLabel('Signature name',{exact:true}).fill('Created from accepted observation');
  await expect(page.getByText('The server supplies the accepted fingerprint and exact raw basename. Continue with a name and labels below.',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Save signature revision',exact:true}).click(); await expect(page.getByRole('status')).toContainText('Signature revision saved');
  const derived=await (await page.request.get('/api/v1/signatures?query=Created%20from%20accepted')).json(); expect(derived.items[0].origin).toBe('FROM_OBSERVATION'); expect(derived.items[0].checksum).toBe(record.checksum);
  await page.getByRole('button',{name,exact:true}).click(); await page.getByLabel('Signature enabled',{exact:true}).uncheck(); await page.getByRole('button',{name:'Save signature revision',exact:true}).click();
  await expect.poll(async()=> (await (await page.request.get('/api/v1/signatures/'+signature.id)).json()).enabled).toBe(false);
  await expect.poll(async()=> (await (await page.request.get('/api/v1/observations/'+observation.id+'/signatures')).json()).items.map((f:{signature:{id:string}})=>f.signature.id),{timeout:60000}).not.toContain(signature.id);
  await inspect(); await expect(page.getByLabel('Location memo',{exact:true})).toHaveValue('Manual note survives signature disable');
  await expect(page.getByRole('region',{name:'Signature findings'})).toContainText('Created from accepted observation');
  await page.getByRole('link',{name:'Signatures',exact:true}).click(); await page.getByLabel('Export format',{exact:true}).selectOption('JSON');
  await page.getByRole('button',{name:'Build catalog export',exact:true}).click(); const download=page.getByRole('link',{name:'Download JSON catalog',exact:true}); await expect(download).toBeVisible({timeout:45000});
  const response=await page.request.get((await download.getAttribute('href'))!); expect(response.ok()).toBe(true);
  expect(response.headers()['content-disposition']).toContain('attachment; filename="signature-catalog-');
  const envelope=await response.json(); expect(envelope.schemaVersion).toBe(1); expect(envelope.signatures.find((r:{id:string})=>r.id===signature.id).memo).toBe(record.memo);
  await page.screenshot({path:testInfo.outputPath('m4-catalog.png'),fullPage:true});
  await page.setViewportSize({width:680,height:900}); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:testInfo.outputPath('m4-catalog-responsive.png'),fullPage:true});
});
